// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXaw9zLZg-OTm7ofa1bzX_XbT7-V1N6zY',
    appId: '1:174945359533:web:7d23607a93c6e279dd5824',
    messagingSenderId: '174945359533',
    projectId: 'solar-amc-app-xkoe90',
    authDomain: 'solar-amc-app-xkoe90.firebaseapp.com',
    storageBucket: 'solar-amc-app-xkoe90.firebasestorage.app',
    measurementId: 'G-5NTWVGEGH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALt9nWEiHKE9xqt83unr0SfcjgM7k0IjY',
    appId: '1:174945359533:android:0279140254e9f750dd5824',
    messagingSenderId: '174945359533',
    projectId: 'solar-amc-app-xkoe90',
    storageBucket: 'solar-amc-app-xkoe90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhC8Px_tk3wXptAj0eKm-LbDIwa2Mr-6E',
    appId: '1:174945359533:ios:ed28c35374761495dd5824',
    messagingSenderId: '174945359533',
    projectId: 'solar-amc-app-xkoe90',
    storageBucket: 'solar-amc-app-xkoe90.firebasestorage.app',
    androidClientId: '174945359533-88eb8q074r90qp198p4dh4c4pcdnut3n.apps.googleusercontent.com',
    iosClientId: '174945359533-l2u1361s17sgfnmek6rvjtr54v6ei6f0.apps.googleusercontent.com',
    iosBundleId: 'org.nogginhausen.solaramcapp.dev',
  );

}